### PR TITLE
Add leading zeros

### LINKED ISSUE #1: Add leading 0
The directory listening looks problematic. Can you please add leading zeros 😜?

### PR DESCRIPTION
**Pull request by robinboening**
Closes https://github.com/bascht/dotfiles/issues/1

### CODE REVIEW

**Comment by bascht** [comment]
> Sorry, we could not display the entire diff because too many files (1,700) changed.

# :grimacing:

**Comment by bascht** [comment]
Could you fix the "test" "suite" ? :-)

**Comment by robinboening** [comment]
haha sure - give me a sec

**Comment by robinboening** [comment]
Done by amending to 91b1e4d. Also added another thing.

**Comment by robinboening** [comment]
Why the heck does github count 1701 changed files on 91b1e4d

In fact 2000 files had been changed:
- 1998 renamed .dot files (999 deleted, 999 added)
- dot.rb
- dot_test.rb

I can proof that this is correct:

```
$ git whatchanged e957ddec281e063176842a022704ac4922c85c47..91b1e4d42c09337241acb77e6d4fc9f6e6710004 --format=oneline | wc -l
```

Result: 2001 (includes the commit message as the first line)

**Comment by bascht** [comment]
We might break GitHub.
Worth a try.

**Comment by pxlpnk** [comment]
\o/

**Pull request merged**
